# Generated by Django 3.2.3 on 2021-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', editable=False, max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('eaddress', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('zip', models.IntegerField(default='', editable=False)),
                ('state', models.TextField(max_length=150)),
                ('city', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Passwd', models.CharField(max_length=30)),
            ],
        ),
    ]
