# Generated by Django 3.2.3 on 2021-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
