# Generated by Django 3.2.3 on 2021-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_application_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fname',
            field=models.CharField(max_length=50),
        ),
    ]
