# Generated by Django 3.2.3 on 2021-07-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(max_length=150),
        ),
    ]
