# Generated by Django 3.2.3 on 2021-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('address', models.TextField(max_length=30)),
                ('zip_code', models.IntegerField(default='')),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('business_strategy', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Passwd', models.CharField(max_length=30)),
            ],
        ),
    ]
