# Generated by Django 3.2.3 on 2021-07-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empower', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
